version: "3.7"
services:
  # openVino model server service
  openvino_mode_server:
    image: openvino/ubuntu18_model_server:latest
    container_name: ovaas_model_server
    tty: true
    volumes: 
        - ./model:/models/face-detection/1
    # ports: 
    #     - 9000:9000
    environment: 
        - LOG_LEVEL=DEBUG
    networks: 
        - dev-network
    command: /ie-serving-py/start_server.sh ie_serving model --model_path /models/face-detection --model_name face-detection --port 9000  --shape auto

  # local
  python:
    build:
      context: ./
      dockerfile: Dockerfile
    image: ovaas_python:latest
    container_name: python
    tty: true
    volumes:
      - .:/home
    networks:
      - dev-network

# Docker Networks
networks:
  dev-network:
    driver: bridge
